// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_ixbZjbOr2QthD7ABm-joWLsVyuW_F0',
    appId: '1:31174330467:web:7831595d6a81559cd45056',
    messagingSenderId: '31174330467',
    projectId: 'chatapp-20a0b',
    authDomain: 'chatapp-20a0b.firebaseapp.com',
    storageBucket: 'chatapp-20a0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD975u4xs_1FDKCz1xphGa6OIio-FmKR2I',
    appId: '1:31174330467:android:1b91f72dea6bad0dd45056',
    messagingSenderId: '31174330467',
    projectId: 'chatapp-20a0b',
    storageBucket: 'chatapp-20a0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQxdUvftFywyi6gFYrvKPRA9T6tVstzbw',
    appId: '1:31174330467:ios:1541fe00ad73fd2cd45056',
    messagingSenderId: '31174330467',
    projectId: 'chatapp-20a0b',
    storageBucket: 'chatapp-20a0b.appspot.com',
    iosClientId: '31174330467-n0ud1mscppl16qm3qkcu74uiivkdl6gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chapapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQxdUvftFywyi6gFYrvKPRA9T6tVstzbw',
    appId: '1:31174330467:ios:4dfb1f0df16d6fa9d45056',
    messagingSenderId: '31174330467',
    projectId: 'chatapp-20a0b',
    storageBucket: 'chatapp-20a0b.appspot.com',
    iosClientId: '31174330467-r2tjjup22s9kpilf2u7sk6cuueabp4mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chapapp.RunnerTests',
  );
}
